version: '3'

services:

  uvicorn:
    build:
      context: .
      dockerfile: Dockerfile-uvicorn-dev
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/app:/container/app
      - ./backend/migrations:/container/migrations
      - ./backend/alembic.ini:/container/alembic.ini

  postgres: 
    image: postgres:14.0-alpine
    restart: always
    # volumes: 
      # - ./backend/postgres:/var/lib/postgresql/data:rw no data save
    environment:
      POSTGRES_USER: "smp_user"
      POSTGRES_PASSWORD: "smp_password"
      POSTGRES_DB: "smp_db"
      PGDATA: "/var/lib/postgresql/data"
    ports:
        - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "81:80"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    volumes: 
      - "./backend/elastic/data:/usr/share/elasticsearch/data"
      - "./backend/elastic/config/hunspell:/usr/share/elasticsearch/config/hunspell"
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      ELASTIC_PASSWORD: "123"
      xpack.security.enabled: "false"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - 5601:5601
  
  nginx:
    image: nginx
    restart: always
    ports:
      - "4444:80"
    volumes:
      - "./backend/app:/usr/share/nginx/html"