FROM python:3.9
WORKDIR /container
COPY ./requirements.txt /container/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /container/requirements.txt
CMD ["uvicorn", "--reload", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
