version: '3'

services:

  uvicorn:
    build:
      context: .
      dockerfile: Dockerfile-uvicorn
    restart: always
    volumes:
      - ./backend/app:/container/app
      - ./backend/nginx/share/static:/container/app/static
      - ./backend/alembic:/container/alembic

  postgres: 
    image: postgres:14.0-alpine
    restart: always
    volumes: 
      - ./backend/postgres/data:/var/lib/postgresql/data:rw
      - ./backend/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "smp_user"
      POSTGRES_PASSWORD: "smp_password"
      POSTGRES_DB: "smp_db"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    restart: always
    volumes: 
      - "./backend/elastic/data:/usr/share/elasticsearch/data"
      - "./backend/elastic/backup:/usr/share/elasticsearch/backup"
      - "./backend/elastic/config/hunspell:/usr/share/elasticsearch/config/hunspell"
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      ELASTIC_PASSWORD: "123"
      xpack.security.enabled: "false"
      discovery.type: single-node
      path.repo: /usr/share/elasticsearch/backup
    ports:
      - "9200:9200"
      - "9300:9300"

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - "./backend/nginx/share:/share"
      - "./backend/nginx/templates:/etc/nginx/templates"
      - "$SSL_CERT:/etc/nginx/ssl/cert.crt"
      - "$SSL_CERT_KEY:/etc/nginx/ssl/certkey.crtkey"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx # Template resolve path
      - SERVER_NAME
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"

# TODO: Restore elasticsearch backup (container with curl?)
# TODO: NPM Builder container