"""empty message

Revision ID: 0e961e7368dc
Revises: 
Create Date: 2022-08-28 05:08:59.855991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e961e7368dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('album_artist',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('album_id', 'artist_id')
    )
    op.create_index(op.f('ix_album_artist_album_id'), 'album_artist', ['album_id'], unique=False)
    op.create_index(op.f('ix_album_artist_artist_id'), 'album_artist', ['artist_id'], unique=False)
    op.create_table('album_relations',
    sa.Column('id1', sa.Integer(), nullable=False),
    sa.Column('id2', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id1'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['id2'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id1', 'id2')
    )
    op.create_index(op.f('ix_album_relations_id1'), 'album_relations', ['id1'], unique=False)
    op.create_index(op.f('ix_album_relations_id2'), 'album_relations', ['id2'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('songs', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_id'), 'playlists', ['id'], unique=False)
    op.create_index(op.f('ix_playlists_user_id'), 'playlists', ['user_id'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('songs', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queues_user_id'), 'queues', ['user_id'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_album_id'), 'songs', ['album_id'], unique=False)
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_table('user_album',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'album_id')
    )
    op.create_index(op.f('ix_user_album_album_id'), 'user_album', ['album_id'], unique=False)
    op.create_index(op.f('ix_user_album_user_id'), 'user_album', ['user_id'], unique=False)
    op.create_table('user_artist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'artist_id')
    )
    op.create_index(op.f('ix_user_artist_artist_id'), 'user_artist', ['artist_id'], unique=False)
    op.create_index(op.f('ix_user_artist_user_id'), 'user_artist', ['user_id'], unique=False)
    op.create_table('song_artist',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'artist_id')
    )
    op.create_index(op.f('ix_song_artist_artist_id'), 'song_artist', ['artist_id'], unique=False)
    op.create_index(op.f('ix_song_artist_song_id'), 'song_artist', ['song_id'], unique=False)
    op.create_table('song_tag',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'tag_id')
    )
    op.create_index(op.f('ix_song_tag_song_id'), 'song_tag', ['song_id'], unique=False)
    op.create_index(op.f('ix_song_tag_tag_id'), 'song_tag', ['tag_id'], unique=False)
    op.create_table('user_song',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'song_id')
    )
    op.create_index(op.f('ix_user_song_song_id'), 'user_song', ['song_id'], unique=False)
    op.create_index(op.f('ix_user_song_user_id'), 'user_song', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_song_user_id'), table_name='user_song')
    op.drop_index(op.f('ix_user_song_song_id'), table_name='user_song')
    op.drop_table('user_song')
    op.drop_index(op.f('ix_song_tag_tag_id'), table_name='song_tag')
    op.drop_index(op.f('ix_song_tag_song_id'), table_name='song_tag')
    op.drop_table('song_tag')
    op.drop_index(op.f('ix_song_artist_song_id'), table_name='song_artist')
    op.drop_index(op.f('ix_song_artist_artist_id'), table_name='song_artist')
    op.drop_table('song_artist')
    op.drop_index(op.f('ix_user_artist_user_id'), table_name='user_artist')
    op.drop_index(op.f('ix_user_artist_artist_id'), table_name='user_artist')
    op.drop_table('user_artist')
    op.drop_index(op.f('ix_user_album_user_id'), table_name='user_album')
    op.drop_index(op.f('ix_user_album_album_id'), table_name='user_album')
    op.drop_table('user_album')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_album_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_queues_user_id'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_playlists_user_id'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_album_relations_id2'), table_name='album_relations')
    op.drop_index(op.f('ix_album_relations_id1'), table_name='album_relations')
    op.drop_table('album_relations')
    op.drop_index(op.f('ix_album_artist_artist_id'), table_name='album_artist')
    op.drop_index(op.f('ix_album_artist_album_id'), table_name='album_artist')
    op.drop_table('album_artist')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
