artists_random = [
    "Motëm",
    "One Man Book",
    "Paweł Feszczuk",
    "The Agrarians",
    "Makaih Beats",
    "Mangrove",
    "Radarsat-1",
    "Fengir",
    "Marcos H. Bolanos",
    "A.J.",
    "Lobo Loco",
    "Alena Smirnova",
    "Sikh Knowledge",
    "Synaptic",
    "DKSTR",
    "Shaolin Dub",
    "KOΔƎK",
    "Ketsa",
    "HoliznaCC0",
    "Lazer Falcon",
    "Joxaren",
    "Coco Bryce",
    "Nutmeg",
    "The Crayon Industry",
    "Dee Yan-Key",
    "Derek Clegg",
    "Smoked Meat Fax Machine",
    "RPG-H8R",
    "Koi-discovery",
    "Levon Zoltar",
    "Peter Drew",
    "Mr Smith",
    "Daniela Salvia",
    "Citofono",
    "Skweee Perry",
    "DJ Puffin",
    "Bio Unit",
    "Matt Oakley",
    "Ixvo-Exvo",
    "Independent Music Licensing Collective (IMLC)",
    "ДДТ",
    "Наутилус Помпилиус",
    "Юрий Антонов",
    "Марк Бернес",
    "Лев Лещенко",
    "Михаил Ножкин",
    "Владимир Златоустовский",
    "Ансамбль имени АВ Александрова",
    "Александр Градский",
    "Любэ",
    "Наутилус Помпилиус",
    "Олег Митяев",
    "Константин Никольский",
    "Муслим Магомаев",
    "ВИА Синяя птица",
    "Майя Кристалинская",
    "Кино",
    "Юрий Визбор",
    "Майя Кристалинская",
    "Владимир Высоцкий",
    "Владимир Высоцкий",
    "Любэ",
    "Марк Бернес",
    "Песняры",
    "Валерий Ободзинский",
    "Олег Анофриев",
    "Эдуард Хиль",
    "Кипелов",
    "Кино",
    "Альберт Асадуллин",
    "Игорь Корнелюк",
    "Разные исполнители",
    "Аида Ведищева",
    "Ольга Воронец",
    "Разные исполнители",
    "Григорий Лепс",
    "Владимир Трошин",
    "ДДТ",
    "Аквариум",
    "Наутилус Помпилиус",
    "Разные исполнители",
    "Песняры",
    "Владимир Макаров",
    "Таисия Калинченко",
    "Юрий Кукин",
    "Муслим Магомаев",
    "Александр Лосев",
    "Алла Пугачёва",
    "Разные исполнители",
    "Людмила Сенчина",
    "Таисия Калинченко",
    "Марк Бернес",
    "Разные исполнители",
    "Пикник",
    "Цветы",
    "Эдуард Хиль",
    "Георг Отс",
    "Веселые ребята",
    "Людмила Сенчина",
    "Леонид Утёсов",
    "Валерий Ободзинский",
    "Алиса",
    "Владимир Высоцкий",
    "Людмила Зыкина",
    "Таисия Калинченко",
    "Фёдор Шаляпин",
    "Эдуард Хиль"
]
albums_random = [
    "City Slacker",
    "1.17.10.: Live Together.",
    "Gamer Beats!",
    "Cloud Cover",
    "A Day at the Sea",
    "Musical Menu",
    "Let the Journey Begin EP",
    "New Launch by Ketsa",
    "Airbit",
    "Joint Force",
    "Depression",
    "Float",
    "Metro",
    "Streetwise Hercules",
    "Bedding",
    "Lost",
    "Export",
    "Post-Morphose",
    "Free and Beautiful",
    "Iron Logic",
    "Dimensions",
    "Skweee Inna Dancehall",
    "Old Town Worry",
    "Lore!",
    "Deadly War",
    "Fredson Drive",
    " Remastered)",
    "Growth",
    "Content",
    "Generator",
    "The New World",
    "True Stories"
]

titles_random =[
    "New Launch",
    "Melody Outro",
    "Blue-Ones",
    "Holla Back Girl",
    "Death Valley",
    "AB CD",
    "Down in the Knucker Hole",
    "Chromatismus",
    "Victory Trail",
    "Allright in Lousiana",
    "Melody Intro",
    "Harmless Vices",
    "Jello",
    "Cress Riddim",
    "Creepers",
    "Glass Beach",
    "La-Rona",
    "Therapy",
    "Not For You",
    "Deja Vu",
    "No-See",
    "Döner Djinn",
    "Depression",
    "South Shore Strut",
    "Welcome to Your Westworld",
    "The Paths Which Choose Us",
    "Happy-Diversion",
    "Complete Me Sometimes",
    "Bed5",
    "Sitting-Fog",
    "Mist",
    "Midnight-Ambience",
    "Shadow-Man",
    "A Dream that Came True",
    "Legends",
    "On The Freeway",
    "Frieden",
    "Trace-da-Funk-instrumental",
    "Righteous",
    "Temple-Life",
    "Slice-of-Sun",
    "Monsters of the past",
    "If-I-Left",
    "Uptown",
    "Soon-Come",
    "Soul-Work",
    "Depression Part 2",
    "If-I-Could-Remember",
    "Say Grace For Me",
    "Big-D",
    "Oriental Waltz (Piano)",
    "Relative to Closest Home",
    "Reworking",
    "Dark Texture",
    "Moonshine",
    "Pillows",
    "Final Level",
    "Sunnyside",
    "Tuffa Scout",
    "Blue-Moons",
    "No-Wing",
    "Settle-Scores",
    "Head-in-Clouds",
    "In The Jungle",
    "rainday",
    "Love-Heart",
    "BornKing",
    "Where the Sun Set",
    "Strategy",
    "Big Grey Man",
    "Progress",
    "Me and You",
    "New Holy Verse",
    "In Space",
    "Beetlejuice",
    "Just-Because",
    "Cloud Cover",
    "Before Too Long",
    "Gone Is The Way",
    "Told Me Early",
    "Lullaby for a Robot",
    "In The City",
    "Motion-Forward",
    "She-Calls",
    "Proud",
    "Catch and Release",
    "Take-Away",
    "Glow-Flow",
    "Synchronised",
    "BlueTrue",
    "Busking In the SunLight",
    "buskers",
    "Jenny Greenteeth",
    "Bed4",
    "Empty Head",
    "Happy  Dance",
    "Cloud-Dream",
    "Icar Fell",
    "Smokey-Mountains",
    "Japonaise",
    "Support Bubble",
    "New-World-Order",
    "A New Fate",
    "Forgotten-Days",
    "Lullaby Sweet Dreams",
    "How-Ya-Mean",
    "Three Feet Of Snow",
    "If-You-re-Wondering",
    "You got my Horses",
    "A Walk Through Dimension",
    "Space Cop",
    "kite flying",
    "Deep Window",
    "Depth of You",
    "Protective Spirits",
    "Self Destruction",
    "glide",
    "Bless-Ups",
    "New Delta Mission",
    "Post-morphose",
    "Slinky",
    "Stupid Song",
    "Goodbye Good Times",
    "sailing day",
    "Place on my Bonfire",
    "Dem-Wicked",
    "Slow-Silent",
    "Coins",
    "The Kid who played Alone",
    "Aced-It",
    "Crooked Townie",
    "Lost-On-Country-Roads",
    "Satellites",
    "Busted AC Unit",
    "As the Sunshine Returns",
    "Fried",
    "Promenade",
    "Heart Method",
    "The Giant of Trendle Hill",
    "Dreaming of Water",
    "We-Know",
    "Every Page is a Truth",
    "OverBlow",
    "Playing-Catch",
    "GODANDRAM",
    "Green North",
    "Don't you dare to breathe",
    "Rekindle",
    "CD Leroy Says No to Guns",
    "Blues about Mary Roose - Retromix",
    "Battleground",
    "Voight-Kampff",
    "a Chat by the fire",
    "Bus Stop",
    "Bed1",
    "Beam",
    "This-Way-For-Joyous-Street",
    "Sun-Breaks-The-Clouds",
    "Traveling to Lousiana - Soft Delay",
    "Juice",
    "Poppy",
    "Speedy Delta",
    "The Greaser",
    "Loving the Loving",
    "When-My-Eyes-Are-Closed",
    "Presetum Operandi",
    "Aloft",
    "Not Today",
    "Synthemania Riddim",
    "Restless",
    "End Credits",
    "Time For Poetry",
    "Rain-Soaked Window",
    "Bohemian Groove",
    "Earth-and-the-Moon",
    "Starfire",
    "Barry's Revenge",
    "Oriental Waltz (Orchestral)",
    "On a Tokyo Train",
    "Soul-Love",
    "I Won't Let You Down",
    "Snow-Dawn",
    "Get up and Go",
    "Recluse",
    "Three Feet Of Snow Part 2",
    "Eternal-Funk-Palace",
    "Manwell",
    "Failed Rendez-Vous",
    "Walk the Walk",
    "Yallery Brown",
    "Airflow",
    "Testing your limits",
    "Run with a power of a thousand soldiers",
    "Bed3",
    "Risen",
    "A Simple Life",
    "Watching the Stars",
    "Augustine's Restless Heart",
    "Occam's Sikhweee",
    "Spring",
    "Walpurgis Night",
    "Abiogenesis Musical Poem",
    "Farewell Eternity",
    "Unify",
    "Falling-Fort",
    "Derived",
    "Enough",
    "Bonus Life",
    "Examples",
    "Lilith",
    "The Gump",
    "Deeper-Roots",
    "Work Wonders",
    "Halloween",
    "Melting-Stars",
    "Epic Revealing a Secret",
    "Brain",
    "beach stroll",
    "Mermaids-Trapped",
    "The-Fayre",
    "Self-Sabotage",
    "Cellularr",
    "If You Waited",
    "The day it all began and it all ended",
    "Rah Rah Rah",
    "Old-Thoughts",
    "Hairy Hands!",
    "Running Eiskrokodil",
    "Hot Sand",
    "Infinite Patience",
    "Times 9",
    "You & my Friend",
    "Bamboo Shoots and Ladders",
    "Can-t-touch-me",
    "MXGHTY",
    "Can't Wait",
    "Triumph",
    "Copper Coins",
    "Stingy Jack",
    "Traveling with Corina - Long",
    "ocean view",
    "A Yankees Southern Blues",
    "paddleboat race",
    "From-the-Beast",
    "summer breeze",
    "All Night Long - Guitarversion",
    "Grave Yard Magic",
    "Bursting",
    "Volery",
    "Wind-it-Up",
    "Fireflies",
    "Christmas Bells",
    "Pull Oscillator",
    "Slides",
    "Within-Time",
    "Twirling Twins",
    "Risco Verde",
    "Full Circles",
    "Trumpets-of-Jericho",
    "Life's Rhythms",
    "Pride",
    "Nowhere To Be, Nothing To Do",
    "broken-origami",
    "Needless-to Say",
    "Hold the Ace",
    "In Between Moments (Motëm's Poser Mix)",
    "Virtual Love",
    "Great Beginnings",
    "Invisible",
    "SeaFood",
    "Dr Dan Will See You Now",
    "Lullaby Sweet Dreams (Piano)",
    "Arising",
    "Surrendered",
    "Suntax",
    "Bed2",
    "Burning Sunshine",
    "For Venus",
    "Get Down",
    "Souvenir",
    "Moderate Passion Tango",
    "Golden Teacher",
    "Rince",
        "Это всё",
    "Что такое осень",
    "Я хочу быть с тобой",
    "Анастасия",
    "Моё богатство",
    "Двадцать лет спустя",
    "Для меня нет тебя прекрасней",
    "Тёмная ночь",
    "День Победы",
    "Последний бой",
    "Вечный огонь (От героев былых времён)",
    "Священная война",
    "Как молоды мы были",
    "Там за туманами",
    "Дыхание",
    "В землянке (Бьётся в тесной печурке огонь)",
    "Катюша",
    "Как здорово, что все мы здесь сегодня собрались",
    "Врагу не сдаётся наш гордый «Варяг»",
    "Музыкант",
    "Луч солнца золотого",
    "Клён",
    "Старый клён",
    "В последнюю осень",
    "Звезда по имени Солнце",
    "Группа крови",
    "Хочу перемен",
    "Милая моя (Всем нашим встречам разлуки, увы, суждены)",
    "Нежность",
    "Я тебя никогда не забуду",
    "Не стреляй!",
    "Он не вернулся из боя",
    "Песня о друге",
    "Позови меня тихо по имени",
    "Я люблю тебя жизнь",
    "Беловежская пуща",
    "Восточная песня",
    "Есть только миг",
    "Ходит песенка по кругу",
    "Голубые города",
    "Песня о друге",
    "Я свободен",
    "Кукушка",
    "Стук",
    "Мой рок-н-ролл",
    "Дорога без конца",
    "Город, которого нет",
    "В лесу прифронтовом",
    "Лесной олень",
    "Гляжу в озёра синие",
    "Ой, мороз, мороз!",
    "Рюмка водки на столе",
    "Подмосковные вечера",
    "Дождь",
    "Город",
    "Последнее письмо",
    "Ой ты, степь широкая ",
    "Эхо любви",
    "Белоруссия",
    "На всю оставшуюся жизнь",
    "Последняя электричка",
    "Золушка",
    "За туманом (А я еду, а я еду за туманом)",
    "Королева красоты",
    "Звездочка моя ясная",
    "Не отрекаются, любя",
    "Песня о тревожной молодости",
    "Белой акации гроздья душистые",
    "Веселый ветер ",
    "Враги сожгли родную хату",
    "Тонкая рябина",
    "Египтянин",
    "Летний вечер",
    "Песня без слов",
    "Вечерняя песня",
    "Я к тебе не подойду",
    "Люблю",
    "Серёжка ольховая",
    "Степь да степь кругом",
    "Ольга",
    "Случайный вальс",
    "Эти глаза напротив",
    "Спокойная ночь",
    "Место для шага вперед",
    "Трасса Е-",
    "Веретено",
    "Охота на волков",
    "А годы летят",
    "Любовь и разлука",
    "Дубинушка ",
    "А люди уходят в море",
    "Течет река Волга",
    "Стерх",
    "Нам с тобой",
    "Кончится лето",
    "Красное на черном",
    "Дождь",
    "Последняя поэма",
    "Поклонимся великим тем годам",
    "Пачка сигарет"
]